### ISSUE TITLE
On-going development

### ISSUE THREAD

**Issue by CMCDragonkai** [rohitjha/MPL#1]
Will this be developed further? This seems to pack together a lot of functionality, but what about the more specialised packages as listed on Haskell Math wiki https://wiki.haskell.org/Applications_and_libraries/Mathematics?

**Comment by rohitjha** [comment]
I had been really busy with my work for the past few months, but I now have some time on my hands. Honestly, I would like to develop this further. I'll try to add functionality to the existing modules. Also, I would be grateful if you can provide your suggestions.

When I had created this DSL, there weren't as many packages liked on the wiki. My objective was to created a DSL understandable to mathematicians, without them really needing to learn Haskell.

**Comment by CMCDragonkai** [comment]
I see. My first question would be, why didn't you use template haskell
instead of the preprocessor?

Secondly, does your language deal with infinite precision arithmetic?

**Comment by rohitjha** [comment]
The translation of source code from the DSL to Haskell was trivial enough to use a simple preprocessor instead of AST manipulation. Can you help me understand what advantages would Template Haskell offer?

Also, the language does handle infinite precision arithmetic since it uses the Integer type over Int in most places.
